---
- name: Local Playbook
  hosts: localhost
  become: true

  tasks:
  - name: Install common programs
    apt:
     name:
#      - curl
#      - wget
      - htop
#      - mc
      - tmux
#      - tree
     state: present

  - name: Create source.list for Proxmox
    copy:
     content: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
     dest: "/etc/apt/sources.list.d/pve-no-sub.list"

  - name: download Proxmox GPG keys
    get_url:
     url: " https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg"
     dest: "/etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg"
     mode: 0755

  - name: Update and upgrade apt packages
    apt:
     upgrade: yes
     update_cache: yes
     cache_valid_time: 86400 #One day

  - name: Install Proxmox Kernel
    apt:
     name: pve-kernel-6.2
     state: present

