---
- name: Local Playbook
  hosts: localhost
  become: true

  tasks:
  - name: Install common programs
    apt:
     name:
      - htop
      - mc
      - tmux
      - tree
     state: present

  - name: Install PVE
    apt:
     name:
      - proxmox-ve
      - postfix
      - open-iscsi
     state: present

  - name: Remove the Debian Kernel
    ansible.builtin.shell: apt remove linux-image-amd64 'linux-image-6.1*'

  - name: Update grub
    ansible.builtin.shell: update-grub

  - name: Remove os-prober
    apt:
     name: os-prober
     state: remove

